# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#production:
 # <<: *default
  #database: db/production.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: fotos_dev
  pool: 5
  username: fotos
  password: fotos

test:
  adapter: postgresql
  encoding: unicode
  database: fotos_test
  pool: 5
  username: fotos
  password: fotos